### ISSUE TITLE
Please add one more site

### ISSUE THREAD

**Issue by momu** [tankaru/JumpToOSMChangesetAnalyzer#5]
Hi @tankaru , thanks a lot for the extension.

Is it possible for you to add this site

    https://resultmaps.neis-one.org/osm-change-viz

osm-change-viz shows changesets similar to achavi and expects the changeset id:

`https://resultmaps.neis-one.org/osm-change-viz?c=<changeset>`

**Comment by tankaru** [comment]
Thank you.
I've updated the code and the browser extension.
Check it.

**Comment by momu** [comment]
Thanks, works fine.
